### PR TITLE
Fix cmake compilation issue in centos7

### PR DESCRIPTION
**Pull request by kaustubh-d**
This fixes the compilation issue on centos 7. The quotes escaping fails. And seems its not really required for the passed in macro used to generate evhtp.pc. 
Another way was to do -DPROJECT_VERSION=\\\\\"${PROJECT_VERSION}\\\\\" (three '\'), but since quotes is not really required, I feel it can be ignored.

....
Name: libevhtp
Description: A more flexible replacement for libevent's httpd API
Version: 1.2.11
....

### CODE REVIEW

**Comment by kaustubh-d** [comment]
Please Note that this is required to compile version > 1.2.11.

**Comment by kaustubh-d** [comment]
@ellzey Can you please review this change. Will be good to have this is in so that compilation also works on centos 7.

**Comment by kaustubh-d** [comment]
Thanks a lot @ellzey for merging this! Can you please let me know when are you planning to release next version, may be 1.2.12?

**Comment by ellzey** [comment]
I will, as soon as I figure out how to fix the resume bug without libevent 2.2

**Comment by kaustubh-d** [comment]
cool, Thank you!

**Pull request merged**
