### PR TITLE
fix memory leak & add thread exit callback

### PR DESCRIPTION
**Pull request by jgli**
REF

### CODE REVIEW

**Comment by ellzey** [comment]
Got it, making some modifications for you to review. Will be done in a few minutes.

**Comment by ellzey** [comment]
@jgli can you look at https://github.com/ellzey/libevhtp/commit/b6340022fcec9009aa33f55377bed576813c580e and tell me if that works for you?

**Comment by ellzey** [comment]
If it's cool with you, I'm going to merge your additions plus mine.

**Comment by jgli** [comment]
It's cool, and it works good. Thanks!

**Comment by ellzey** [comment]
Awesome. And I forgot to thank you for finding that bug.

**Pull request merged**
