### PR TITLE
HTTP 304 code compliant response

### PR DESCRIPTION
**Pull request by car3ca**
A 304 HTTP response should(or must) not have a "Content-Type" header field (on my understanding).
This way it is possible to create such response.

### CODE REVIEW

**Comment by adamel** [comment]
1. Do not include merges from upstream in pull requests. git rebase your work onto the current upstream instead.
2. Responses to HEAD requests always includes Content-Type but never a body, so the patch is broken.

Personally I'd like to support responses that shouldn't include a Content-Type by simply removing the automatic adding of Content-Type in _evhtp_create_reply(), forcing any callers to always add a Content-Type header if they want one. What's @ellzey's opinon on a patch doing that?

**Comment by car3ca** [comment]
Thank you for your notes.
It's true, I don't have the HEAD case on my test suite and I missed it.

I agree on not including automatic Content-Type on _evhtp_create_reply() on a future version, but to keep (some) backwards compatibility it could be reasonable enough to add it automatically only with a Content-Length present.

Something like this (if not missing something else):
```C
    if (!content_type && evhtp_header_find(request->headers_out, "Content-Length")) {
        evhtp_headers_add_header(request->headers_out,
                                 evhtp_header_new("Content-Type", "text/plain", 0, 0));
    }
```
What do you think?

**Comment by adamel** [comment]
IMO doing evhtp_header_find() in the library should really be avoided for performance reasons.
As for backward compatibility there has never been any in libevhtp, so I suggest we don't bother with that and concentrate on getting everything to work as well as possible first instead.

**Comment by car3ca** [comment]
Perfornance was one of the reasons I only checked for out_len previously.
You're probably right on just forcing callers to add Content-Type when needed.
Lets wait for @ellzey opinion.

Thank you!

**Comment by car3ca** [comment]
I'll submit a patch removing automatic Content-Type in _evhtp_create_reply().

**Pull request closed without merging**
