### PR TITLE
Add CPack commands to build a debian package.

### PR DESCRIPTION
**Pull request by pusateri**
I know this has been discussed before. I needed to build a debian package for Ubuntu 14.04 LTS and while I know you probably won't merge this pull request as is, it may be useful for others out there.

### CODE REVIEW

**Comment by ellzey** [comment]
This is cool; Though I am a little sceptical of command-line tools being executed, and I think using cpack may be more compatible, like these variables you can set. 

I remember cpack+rpm sucking though, forget why. I will test debs tonight.

```
(01:34:08) ○ [ellzey@EAGAIN] ~/Sandbox  cpack --help-variable-list | grep -i deb
CPACK_DEBIAN_PACKAGE_ARCHITECTURE
CPACK_DEBIAN_PACKAGE_BREAKS
CPACK_DEBIAN_PACKAGE_CONFLICTS
CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
CPACK_DEBIAN_PACKAGE_DEBUG
CPACK_DEBIAN_PACKAGE_DEPENDS
CPACK_DEBIAN_PACKAGE_DESCRIPTION
CPACK_DEBIAN_PACKAGE_ENHANCES
CPACK_DEBIAN_PACKAGE_HOMEPAGE
CPACK_DEBIAN_PACKAGE_MAINTAINER
CPACK_DEBIAN_PACKAGE_NAME
CPACK_DEBIAN_PACKAGE_PREDEPENDS
CPACK_DEBIAN_PACKAGE_PRIORITY
CPACK_DEBIAN_PACKAGE_PROVIDES
CPACK_DEBIAN_PACKAGE_RECOMMENDS
CPACK_DEBIAN_PACKAGE_REPLACES
CPACK_DEBIAN_PACKAGE_SECTION
CPACK_DEBIAN_PACKAGE_SHLIBDEPS
CPACK_DEBIAN_PACKAGE_SUGGESTS
CPACK_DEBIAN_PACKAGE_VERSION
```

**Comment by pusateri** [comment]
This is handy but probably not good for much more than local use.

**Comment by ellzey** [comment]
> This is handy but probably not good for much more than local use.

I disagree, it's very useful; evhtp package's are available on just about every distro except debian-based systems.

**Comment by pusateri** [comment]
It appears that later versions of Ubuntu have now included it in their repositories. I found it in 15.10. But I needed it in 14.04 for a client and was therefore, building it myself. Here is the debian directory for packaging at the Debian site. Maybe you could merge this into your tree so that it builds compliant debian packages.

http://anonscm.debian.org/cgit/collab-maint/libevhtp.git/tree/debian

**Pull request merged**
